### PR TITLE
Publish to Maven

### PR DESCRIPTION
**Pull request by wscsprint3r**

### CODE REVIEW

**Comment by ghislainfourny** [comment]
@wscsprint3r this seems to not pass the test queue. Do we know why?

**Comment by wscsprint3r** [comment]
@ghislainfourny I will fix it, it's probably missing credentials for the new Maven steps, but we probably don't want those integrated into the CI process.

**Comment by wscsprint3r** [comment]
@ghislainfourny I will check and see, maybe we can create a shared key for gpg signing and also have credentials for you and @CanBerker so you can access the repository. For now I can share my credentials with you.

**Comment by ghislainfourny** [comment]
Thanks, Stefan! I also checked and it seems fine to use GPG to sign -- as long as we do not copy over any of its code, nor link it into our jar.

**Pull request merged**
