### PR TITLE
Stick to Trusty distribution in Travis to support Java 8

### PR DESCRIPTION
**Pull request by ghislainfourny**

### CODE REVIEW

**Comment by ghislainfourny** [comment]
Travis dropped support for Java 8. Moving to Java 11 LTS that Spark seems to now support.

**Comment by wscsprint3r** [comment]
@ghislainfourny do we still have a cluster somewhere where we can run this and make sure it works?

**Comment by wscsprint3r** [comment]
Maybe we need to package some extra dependencies or something...

**Comment by ghislainfourny** [comment]
Hi Stefan,

Yes, there is AWS EMR that can be used for this. We can simply deploy a cluster on demand. I recently tested that DataFrames and Spark SQL work well with our jar there.

The DSO is no longer available, unfortunately.

Kind regards,
Ghislain

**Pull request merged**
