### PR TITLE
Substring after

### PR DESCRIPTION
**Pull request by AndreaRinaldi1**
This branch introduces the substring-after builtin function (with two string arguments) as described in the [W3C documentation](https://www.w3.org/TR/xpath-functions-30/#func-substring-after).

### CODE REVIEW

**Comment by wscsprint3r** [comment]
LGTM

**Comment by wscsprint3r** [comment]
@ghislainfourny what do you think about adding an automatic code formatter plug-in like spotless to have consistent code style across the project?

**Comment by ghislainfourny** [comment]
I agree. Would you have the time to look into this? I don't mind much about the "cosmetics" of spaces and tabulations, so you can pick what you like.

Regarding higher level style, I think we should start writing down our architectural decisions, which would make it easier for people joining the project. This is something I'll start working on.

**Comment by AndreaRinaldi1** [comment]
Pulled master and pushed new version, to have a clean merge.
_Waiting for approval to merge..._

**Comment by wscsprint3r** [comment]
@ghislainfourny I can have a look, yes.

**Pull request merged**
