### PR TITLE
Add restaurant dataset

### PR DESCRIPTION
**Pull request by CanBerker**
Dear @ghislainfourny, I will be using the following restaurant dataset (~2500) for rumbleML performance measurements taken from [here](https://github.com/ozlerhakan/mongodb-json-files).

Adding this dataset to the Rumble engine is not necessary for my work by any means. But I wanted to open a PR to ask if you would find such a dataset usable for the project's tests or anything else. Otherwise we can just close this PR and the shared link can stay here for the future if such a need arises.

### CODE REVIEW

**Comment by ghislainfourny** [comment]
Thanks, @CanBerker 

My concern is more about the license to the data, because this does not belong to us. Where does it come from, and under what license is it released? Thanks!

**Comment by CanBerker** [comment]
That is a very good point. The GitHub repo I shared earlier specifies a public domain license for the data. Yet, I am absolutely not an expert on the licensing issues. When I look at the data, I get the feeling it feels that it may have been mined off a food take-away ordering website. I wonder if this would make it subjected to licensing issues.

In any case, to be on the safe side I think it's a good idea to avoid incorporating this data set into Rumble. Should I also try to find a new dataset for the ml measurements or would it be fine for that use-case?

**Comment by CanBerker** [comment]
Listing nice datasets for archiving purposes:
IMDB review data, public domain license, 573913 rows:
https://www.kaggle.com/rmisra/imdb-spoiler-dataset#IMDB_movie_details.json

Online retail data from UCI, no citation request, little over 1.000.000 rows:
https://archive.ics.uci.edu/ml/datasets/Online+Retail+II

HEPMASS dataset from UCI, no citation request,  10.500.000 rows:
https://archive.ics.uci.edu/ml/datasets/HEPMASS

**Comment by ghislainfourny** [comment]
> Listing nice datasets for archiving purposes:
> IMDB review data, public domain license, 573913 rows:
> https://www.kaggle.com/rmisra/imdb-spoiler-dataset#IMDB_movie_details.json
> 
> Online retail data from UCI, no citation request, little over 1.000.000 rows:
> https://archive.ics.uci.edu/ml/datasets/Online+Retail+II
> 
> HEPMASS dataset from UCI, no citation request, 10.500.000 rows:
> https://archive.ics.uci.edu/ml/datasets/HEPMASS

I think that the fact they do not ask for a citation does not in itself allow us to copy the data over. Could you send the responsible persons of uci.edu  an email and ask for an authorization, explaining that this is for testing purposes? It would be great. Thanks!

**Comment by ghislainfourny** [comment]
> > Listing nice datasets for archiving purposes:
> > IMDB review data, public domain license, 573913 rows:
> > https://www.kaggle.com/rmisra/imdb-spoiler-dataset#IMDB_movie_details.json
> > Online retail data from UCI, no citation request, little over 1.000.000 rows:
> > https://archive.ics.uci.edu/ml/datasets/Online+Retail+II
> > HEPMASS dataset from UCI, no citation request, 10.500.000 rows:
> > https://archive.ics.uci.edu/ml/datasets/HEPMASS
> 
> I think that the fact they do not ask for a citation does not in itself allow us to copy the data over. Could you send the responsible persons of uci.edu an email and ask for an authorization, explaining that this is for testing purposes? It would be great. Thanks!

Public domain is fine, though.

**Comment by CanBerker** [comment]
Thanks for pointing this out. In my measurements I have  only used the public domain data. I simply listed the other data sets to archive them in the body of this PR as  'nice finds'. I was hoping they could be handy references for someone in the case a large datasets is needed for measurements in the future.

**Comment by CanBerker** [comment]
@ghislainfourny As discussed, this PR can be closed. The links are merely here for the archiving purposes.

**Pull request closed without merging**
