### PR TITLE
Kryo instance optimization

### PR DESCRIPTION
**Pull request by ghislainfourny**

### CODE REVIEW

**Comment by ghislainfourny** [comment]
@CanBerker Ready for review, and enjoy measuring the queries on this!

**Comment by CanBerker** [comment]
Before "548e8a5 Improve performance" further commit: https://github.com/CanBerker/sparksoniq-dataframe-perf-v1/pull/2

After the most recent "952b572 Optimize More" commit: https://github.com/CanBerker/sparksoniq-dataframe-perf-v1/pull/2

**Comment by CanBerker** [comment]
Each implemented improvement is tested by incrementally adding them to the project. The tests were ran 5 times for each version. The resulting numbers are averaged across 5 runs. 

Q1: Select
Q4: Order
Q5: Groupby

v0 Results ( vanilla, no improvements):
DF-Q1: 252113.4
Q1: 39881.0
DF-Q4: 1411401.8
Q4: 331403.0
DF-Q5: 766243.8
Q5: 305671.8

v1 Results (following Improve performance further commit given above):
DF-Q1: 155034.8
Q1: 37328.8
DF-Q4: 792908.2
Q4: 338868.0
DF-Q5: 496522.2
Q5: 314161.0

v2 Results (following this entire PR - after optimize more commit ):
DF-Q1: 134815.6
Q1: 34606.8
DF-Q4: 682674.8
Q4: 341641.0
DF-Q5: 440575.2
Q5: 319552.0

v3 Results ( implementing caching on orderby and groupby clauses):
DF-Q1: 258722.6
Q1: 132308.4
DF-Q4: 1499679.4
Q4: 290943.4
DF-Q5: 801392.2
Q5: 401897.6

v4 Results ( refactoring the groupby query with 3 columns  to reduce number of actions needed)
DF-Q1: 254485.8
Q1: 35770.8
DF-Q4: 547082.6
Q4: 342715.8
DF-Q5: 566386.0
Q5: 315671.4

Note1: v3 version's result seem weirdly off. Probably the state of the machine wasn't ideal at the time of measurements for reasons unknown to me.

Note2: The query duration for the DF select query seems to have gone up at v3-v4, reason unknown.

Note3: The improvements regarding orderby looks like they have been effective. In the case of groupby, the v2 result seems the best for some reason.

**Comment by ghislainfourny** [comment]
Thanks a lot, Can!

> Each implemented improvement is tested by incrementally adding them to the project. The tests were ran 5 times for each version. The resulting numbers are averaged across 5 runs.
> 
> Q1: Select
> Q4: Order
> Q5: Groupby
> 
> v0 Results ( vanilla, no improvements):
> DF-Q1: 252113.4
> Q1: 39881.0
> DF-Q4: 1411401.8
> Q4: 331403.0
> DF-Q5: 766243.8
> Q5: 305671.8
> 

Perfect, so this is our baseline.

> v1 Results (following Improve performance further commit given above):
> DF-Q1: 155034.8
> Q1: 37328.8
> DF-Q4: 792908.2
> Q4: 338868.0
> DF-Q5: 496522.2
> Q5: 314161.0

Everything improved, great too.


> v2 Results (following this entire PR - after optimize more commit ):
> DF-Q1: 134815.6
> Q1: 34606.8
> DF-Q4: 682674.8
> Q4: 341641.0
> DF-Q5: 440575.2
> Q5: 319552.0


Again a small improvement on all, which is great.

> v3 Results ( implementing caching on orderby and groupby clauses):
> DF-Q1: 258722.6
> Q1: 132308.4
> DF-Q4: 1499679.4
> Q4: 290943.4
> DF-Q5: 801392.2
> Q5: 401897.6

Here this is strange. I think there was an unusual context during the measurements on the machine, because even some of the original measurements took longer. Could you remeasure this?

> v4 Results ( refactoring the groupby query with 3 columns to reduce number of actions needed)
> DF-Q1: 254485.8
> Q1: 35770.8
> DF-Q4: 547082.6
> Q4: 342715.8
> DF-Q5: 566386.0
> Q5: 315671.4
> 
> Note1: v3 version's result seem weirdly off. Probably the state of the machine wasn't ideal at the time of measurements for reasons unknown to me.

Yes, I agree.

> Note2: The query duration for the DF select query seems to have gone up at v3-v4, reason unknown.

It may be that the DF caching has undesirable consequences. We can potentially revert if needed. How much memory do you have on your machine?

The change to grouping on 3 columns was motivated by correctness, not performance, so this had to go in anyway. We probably no longer need to cache on the group by side.

> Note3: The improvements regarding orderby looks like they have been effective. In the case of groupby, the v2 result seems the best for some reason.

**Comment by ghislainfourny** [comment]
@CanBerker I suggest to go ahead and merge this PR, and keep in mind that we may want to revert the DF caching.

**Pull request merged**
