### PR TITLE
Fix contexts for passing outer variables.

### PR DESCRIPTION
**Pull request by ghislainfourny**
Fixes https://github.com/RumbleDB/rumble/issues/244

### CODE REVIEW

**Comment by ghislainfourny** [comment]
@CanBerker this is a fix when outer variables were not bound correctly in some inner clauses (see tests). I fixed it for where and return, but I think there is the same issue for group/order/for and possibly predicates, which should be solvable with the same approach. It would be great if you could take it from there.

The persist() call is hard to test; it is an issue that happens indeterministically on very large data, because the partitions change every time otherwise, leading to null pointer exceptions.

**Comment by CanBerker** [comment]
@ghislainfourny Thanks for catching this oversight with contexts! I will pick this up and apply the same idea to other iterators. 

> The persist() call is hard to test and is addressing an issue with count clauses; 
I understand the persist() call solves the said problem with count completely. Is this correct ?

**Comment by CanBerker** [comment]
I have made a few cosmetic changes mostly converting variables with default access to private and using constructors for sets and maps instead of a consequent putAll operation

**Comment by CanBerker** [comment]
@ghislainfourny I have just noticed one thing from the related issue and pointed it out [here](https://github.com/RumbleDB/rumble/issues/244#issuecomment-562526150)

**Comment by ghislainfourny** [comment]
> @ghislainfourny Thanks for catching this oversight with contexts. I will pick this up and apply the same idea to other iterators.
> 
> > The persist() call is hard to test and is addressing an issue with count clauses;
> 
> I understand the persist() call solves the said problem with count completely. Is this correct ?
> Edit: If so shall we mark this PR's relation with #404 ?

It does. Yes, this fixes #404  .

**Comment by ghislainfourny** [comment]
> @ghislainfourny I have just noticed one thing from the related issue and pointed it out [here](https://github.com/RumbleDB/rumble/issues/244#issuecomment-562526150) It might be good to verify that query example is fully functional as well.

Thank you for the thorough check. The three lines are the second part of the upper query; a query cannot start with a return clause. Does it address your concern?

**Comment by ghislainfourny** [comment]
> I have made a few cosmetic changes mostly converting variables with default access to private and using constructors for sets and maps instead of a consequent putAll operation

I like these changes. Thanks a lot!

**Comment by ghislainfourny** [comment]
> @ghislainfourny Thanks for catching this oversight with contexts. I will pick this up and apply the same idea to other iterators.

@CanBerker thanks a lot!

**Comment by CanBerker** [comment]
> > @ghislainfourny I have just noticed one thing from the related issue and pointed it out [here](https://github.com/RumbleDB/rumble/issues/244#issuecomment-562526150) It might be good to verify that query example is fully functional as well.
> 
> Thank you for the thorough check. The three lines are the second part of the upper query; a query cannot start with a return clause. Does it address your concern?

Exactly, I was confused by that query due to that misunderstanding. It's all good now :)

**Pull request merged**
