### PR TITLE
Prevent redundant vectorization

### LINKED ISSUE #504: RumbleML Optimization: FeaturesCol
Don't perform vectorization with the VectorAssembler for Estimator and Transformers if the column specified in featuresCol is a single column that is already of a vector type (at the moment this can be achieved only by using the LibSVM file reader as users can't create vectors directly)

### PR DESCRIPTION
**Pull request by CanBerker**
Fixes #504

### CODE REVIEW

**Comment by CanBerker** [comment]
Great catch! This was not possible earlier due to the peculiarities of the previous implementation. I will investigate this merging idea again and apply it if possible now.

**Comment by ghislainfourny** [comment]
@CanBerker if the Java CI test passes, I am happy to merge it, just let me know. Since Travis CI is becoming buggy these days, I am considering a migration to GitHub Actions (the tests are already run every time there).

**Comment by CanBerker** [comment]
@ghislainfourny Java CI seems positive, travis is yet again stuck.

**Comment by ghislainfourny** [comment]
@CanBerker I have changed the requirement to the GitHub tests. You can now merge even if Travis test results are not reported, but the GitHub CI passed.

**Comment by CanBerker** [comment]
@ghislainfourny Thanks! I can't merge to master at the moment though due to authorization issues: 
image

**Comment by ghislainfourny** [comment]
@CanBerker I changed a setting, does it work now?

**Comment by CanBerker** [comment]
@ghislainfourny Yes it worked. Thank you

**Pull request merged**
